"""
data/permutation_nulls.py
============================
Four permutation-based controls, each destroying a different, precisely
scoped piece of structure while operating directly on the REAL corpus's
own tokens (unlike data/adversarial_null_model.py, which resamples fresh
signs from marginal distributions). Comparing across all four tells you
WHERE in the corpus the classifiable signal actually lives, because each
one leaves a different piece of real structure intact:

  within_inscription_shuffle: each inscription's own multiset of signs is
    shuffled into a new order, in place. Preserves each inscription's
    exact vocabulary and the corpus's exact unigram frequencies (trivially,
    since no sign is created, destroyed, or moved between inscriptions).
    Destroys ALL within-inscription order, both position (initial/final
    identity) and sequential (bigram+) dependency.

  global_shuffle: every sign token in the whole corpus is pooled and
    reshuffled, then re-cut into inscriptions using the ORIGINAL sequence
    of inscription lengths. Preserves corpus-wide unigram frequency and
    the length distribution exactly. Destroys within-inscription order
    AND which specific signs co-occurred in the same inscription (unlike
    within_inscription_shuffle, which keeps each inscription's own
    vocabulary intact).

  position_preserving_shuffle: for each inscription, the OBSERVED initial
    and final sign (the literal values in that specific inscription, not
    just a marginal distribution) are held fixed in place; only the
    middle signs are shuffled among themselves. This is a stricter,
    per-inscription version of what data/adversarial_null_model.py does
    at the marginal-distribution level. Destroys middle-sequence order
    only; initial/final identity and length are exactly the real values.

  bigram_markov_null: a fresh corpus generated by sampling forward
    through the REAL empirical bigram transition table (not a synthetic
    assumption, not a resampled marginal) -- start each sequence from a
    sign drawn from the real initial-sign distribution, then repeatedly
    draw the next sign from the real P(next | current) table, for the
    real observed length. Preserves real unigram AND real bigram
    (order-1) statistics. Destroys any dependency beyond order-1 (i.e.
    trigram and higher). If the real corpus is still distinguishable from
    THIS control, that is evidence of real structure beyond what a
    bigram model captures; if it is not, most of the predictable
    structure in the corpus is local (order-1).
"""
from __future__ import annotations
import random

from data.loader import Corpus, Inscription
from analysis.ngram import bigram_counts


def within_inscription_shuffle(real_corpus: Corpus, seed: int = 0) -> Corpus:
    rng = random.Random(seed)
    filtered = real_corpus.filter(exclude_damaged=True)
    inscriptions = []
    for ins in filtered.inscriptions:
        seq = list(ins.normalized_signs())
        rng.shuffle(seq)
        inscriptions.append(Inscription(
            inscription_id=f"SHUF-{ins.inscription_id}", signs=seq,
            site="permuted", object_type="unknown",
            reading_direction="R-L", motif="unknown",
        ))
    return Corpus(inscriptions)


def global_shuffle(real_corpus: Corpus, seed: int = 0) -> Corpus:
    rng = random.Random(seed)
    filtered = real_corpus.filter(exclude_damaged=True)
    sequences = filtered.sequences(normalized=True)
    lengths = [len(s) for s in sequences]

    pool = [sign for seq in sequences for sign in seq]
    rng.shuffle(pool)

    inscriptions = []
    cursor = 0
    for i, length in enumerate(lengths):
        seq = pool[cursor:cursor + length]
        cursor += length
        inscriptions.append(Inscription(
            inscription_id=f"GSHUF-{i:05d}", signs=seq,
            site="permuted", object_type="unknown",
            reading_direction="R-L", motif="unknown",
        ))
    return Corpus(inscriptions)


def position_preserving_shuffle(real_corpus: Corpus, seed: int = 0) -> Corpus:
    rng = random.Random(seed)
    filtered = real_corpus.filter(exclude_damaged=True)
    inscriptions = []
    for ins in filtered.inscriptions:
        seq = list(ins.normalized_signs())
        if len(seq) >= 3:
            middle = seq[1:-1]
            rng.shuffle(middle)
            seq = [seq[0]] + middle + [seq[-1]]
        # length 1 or 2: nothing to shuffle, kept exactly as observed
        inscriptions.append(Inscription(
            inscription_id=f"POSSHUF-{ins.inscription_id}", signs=seq,
            site="permuted", object_type="unknown",
            reading_direction="R-L", motif="unknown",
        ))
    return Corpus(inscriptions)


def bigram_markov_null(real_corpus: Corpus, n_inscriptions: int, seed: int = 0,
                         max_length: int = 40) -> Corpus:
    """Generates from the real order-1 (bigram) transition table, including
    a special END token trained on real sequence endings, so that WHEN a
    sequence stops is itself learned from real data rather than imposed
    externally. An earlier version of this function fixed each generated
    sequence's length to a real observed length and let the chain run
    exactly that many steps; that unfairly penalized the null on the
    top_sign_final_share feature, since a chain forced to stop by external
    fiat has no way to reproduce a real "closing sign" tendency that is
    actually encoded in the real P(END | current_sign) distribution.
    Learning END as a normal transition target fixes this: if the real
    corpus's final-position behavior is genuinely just an order-1 effect
    (some signs are simply likely to precede END), this null should
    reproduce it; if it is not (i.e. requires something beyond order-1),
    this null will still fail to reproduce it, and that failure is then
    real evidence rather than an artifact of the generation procedure.
    """
    rng = random.Random(seed)
    filtered = real_corpus.filter(exclude_damaged=True)
    sequences = filtered.sequences(normalized=True)
    sequences = [s for s in sequences if s]

    END = "<END>"
    initial_signs = [s[0] for s in sequences]

    uni_counts, bi_counts = bigram_counts(sequences)
    # add explicit transitions to END after each sequence's real final sign
    end_augmented_bi = dict(bi_counts)
    for s in sequences:
        end_augmented_bi[(s[-1], END)] = end_augmented_bi.get((s[-1], END), 0) + 1

    transitions: dict[str, list[tuple[str, int]]] = {}
    for (a, b), c in end_augmented_bi.items():
        transitions.setdefault(a, []).append((b, c))

    all_signs = list(uni_counts.keys())
    all_weights = list(uni_counts.values())

    def next_sign(current: str) -> str:
        options = transitions.get(current)
        if not options:
            return rng.choices(all_signs, weights=all_weights, k=1)[0]
        signs, weights = zip(*options)
        return rng.choices(signs, weights=weights, k=1)[0]

    inscriptions = []
    for i in range(n_inscriptions):
        seq = [rng.choice(initial_signs)]
        while len(seq) < max_length:
            nxt = next_sign(seq[-1])
            if nxt == END:
                break
            seq.append(nxt)
        if not seq:
            continue
        inscriptions.append(Inscription(
            inscription_id=f"BIMARKOV-{i:05d}", signs=seq,
            site="permuted", object_type="unknown",
            reading_direction="R-L", motif="unknown",
        ))
    return Corpus(inscriptions)
